name: dadata_client
description: Dart package for Dadata.ru API integration. Provides address suggestions, data validation, and enrichment. Compatible with both Flutter and Dart.
version: 0.1.0+1


environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
